### ISSUE TITLE
Make workspace/table/graph deletion UI more obvious/discoverable

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multinet-client#12]
It may not be fully clear to a new user that clicking on the checkboxes for the various item types reveals an option for deletion. We should explore designs that make the deletion option into a truly discoverable affordance.

**Comment by jtomeck** [comment]
@waxlamp while in here working on solutions for this, I'm realizing that I'm not quite sure what the issue is. I use so many applications throughout the day where the expected action is that you select something and then you can do some action to it.

Would it be an acceptable solution to have the action icons always visible on the top, but they're greyed out unless something is selected?

**Comment by waxlamp** [comment]
My vision for this was something like what GMail does: when you hover over an item (workspace, table, or network), the same download and delete icons should appear on the row of the item. Clicking on those would initiate an immediate deletion or download action for just that item.

My thinking is that this aids discoverability by showing you actions to perform as soon as you begin to interact with an item.

If you can set up the icons, then Jake and I can work on hooking them up to make them live.

Let me know what you think.

**Comment by jtomeck** [comment]
Ah, okay. Sounds good!
