### ISSUE TITLE
Upload silently fails for example dataset

### ISSUE THREAD

**Issue by alexsb** [multinet-app/multinet-client#216]
This is a movies dataset in D3 JSON format. No response after a few minutes. 

https://drive.google.com/open?id=1tGDHfAFnYhcGltE5hP2y0R-rHbePDqiq&authuser=alexander.lex%40gmail.com&usp=drive_fs

**Comment by AlmightyYakob** [comment]
It seems the reason for this is that the provided file has ~100 entries in the `nodes`field that are empty objects. The D3 JSON format used by multinet expects each node to have an `id` field, so these empty objects fail during parsing. However, this raises a few good points:

- If an object is found that doesn't contain an `id` field, that individual object should just be ignored, rather than the entire upload failing.
- The client should show that this upload failed, rather than forever waiting for it.
- The client should show the reasons for upload failure.

I can work to address these issues.
