### ISSUE TITLE
Update the view app links to use network in querystring, not graph

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-client#90]
The other option is networkName, waiting on a decision from Roni

**Comment by naglepuff** [comment]
This was partially addressed by #188 . Launching a vis app from the NetworkDetail view will correctly use `network` in the querystring.

There are still some links hard-coded onto the landing page with `&graph=` in the querystring.

**Comment by waxlamp** [comment]
I'm a bit surprised to hear that--the opened apps will need to know to expect `network` in the query arguments rather than `graph`, and I don't think that has been done yet. In my opinion, the query argument parsing should be done in `multinetjs` to relieve the burden of doing so on client applications.

@naglepuff, can you confirm the following?
> Launching a vis app from the NetworkDetail view will correctly use `network` in the querystring.

If this is true, I would expect the vis apps to break.

**Comment by waxlamp** [comment]
> The other option is networkName, waiting on a decision from Roni

`network` is the string we should use.

**Comment by naglepuff** [comment]
> I'm a bit surprised to hear that--the opened apps will need to know to expect network in the query arguments rather than graph, and I don't think that has been done yet. In my opinion, the query argument parsing should be done in multinetjs to relieve the burden of doing so on client applications.

Part of the [initial port](https://github.com/multinet-app/multimatrix/pull/332) of `multimatrix` updates it to expect the query parameter `network`. The same should be done to `multilink` when the port for that is implemented. Are you suggesting that we use `multinetjs` to launch the vis apps from the client? 

> > Launching a vis app from the NetworkDetail view will correctly use `network` in the querystring.

See the code [here](https://github.com/multinet-app/multinet-client/blob/e3201f759bdc84c9af23d5aafcd2a1e348c57eee/src/views/NetworkDetail.vue#L92-L96). I don't think there  was thorough testing of all of these changes, but I imagine that this change did break launching vis apps from the `girder4` branch until the vis apps are updated themselves to anticipate a URL query parameter called `network`. 

As of now, the `girder4` branch of `multinet-client` uses `network` when attempting to launch a vis app from the network detail, and `graph` when launching the hard-coded links from the home page.

**Comment by waxlamp** [comment]
Ok, so all this is happening on the `girder4` branches, which is perfect. Thanks for giving me that extra info.

The homepage links should be updated to say `network` as well--otherwise, when we redeploy the updates versions of everything, those links will break, right?

**Comment by waxlamp** [comment]
> > I'm a bit surprised to hear that--the opened apps will need to know to expect network in the query arguments rather than graph, and I don't think that has been done yet. In my opinion, the query argument parsing should be done in multinetjs to relieve the burden of doing so on client applications.
> 
> [...] Are you suggesting that we use `multinetjs` to launch the vis apps from the client?

I forgot to answer this question earlier, sorry.

My suggestion was that multinetjs include a function that parses the standard query arguments from the URL, so that each client app doesn't have to repeat the same logic every time. That's not a hard requirement for anything currently in flight, just a convenience we should offer to the client app writer via the library.

**Comment by JackWilb** [comment]
Closed in girder4 via #197
